# Generated by Django 4.0.3 on 2022-03-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userkeys',
            old_name='secretkey_enc',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='userkeys',
            old_name='publickey',
            new_name='public_key',
        ),
    ]
