# Generated by Django 4.0.3 on 2022-03-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_secretkey_enc_userkeys_private_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='access',
            options={'verbose_name': 'Доступ', 'verbose_name_plural': 'Доступы'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файл'},
        ),
        migrations.RemoveField(
            model_name='file',
            name='folder',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='folder',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='file',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.file', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
