# Generated by Django 4.0.3 on 2022-03-19 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_info_panel_userpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='panel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.panel'),
            preserve_default=False,
        ),
    ]
