# Generated by Django 4.0.3 on 2022-03-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_access_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Папка')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папка',
            },
        ),
        migrations.RemoveField(
            model_name='access',
            name='file',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='file',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='access',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.folder', verbose_name='Папка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradmin',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.folder', verbose_name='Папка'),
            preserve_default=False,
        ),
    ]
