# Generated by Django 4.0.3 on 2022-03-22 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_folder_remove_access_file_remove_useradmin_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='user',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='user',
            field=models.ManyToManyField(db_index=True, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
