# Generated by Django 4.0.3 on 2022-03-19 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_info_panel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='panel',
            name='users',
        ),
    ]
