# Generated by Django 4.0.3 on 2022-03-19 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_panel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.panel'),
        ),
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publickey', models.BinaryField()),
                ('secretkey_enc', models.BinaryField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
