# Generated by Django 4.0.3 on 2022-03-22 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_remove_useradmin_user_useradmin_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradmin',
            name='user',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
